// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rwxP2NkZ3jFSqRDUBbyEnOPD3vcYDYo',
    appId: '1:140632033053:web:a7f3130f3fe502bfe783f4',
    messagingSenderId: '140632033053',
    projectId: 'groce-ease-e4039',
    authDomain: 'groce-ease-e4039.firebaseapp.com',
    storageBucket: 'groce-ease-e4039.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4HrTr05PVDfv78wG5EU4WAUhC8yLdoCQ',
    appId: '1:140632033053:android:00d5de9833fb4825e783f4',
    messagingSenderId: '140632033053',
    projectId: 'groce-ease-e4039',
    storageBucket: 'groce-ease-e4039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrGQK7_LKpMygAtHCftIjxziU6pU_wYBc',
    appId: '1:140632033053:ios:abf3052d1526b698e783f4',
    messagingSenderId: '140632033053',
    projectId: 'groce-ease-e4039',
    storageBucket: 'groce-ease-e4039.appspot.com',
    iosClientId: '140632033053-uv2joh7e2q54vcvkrjqp4f7ok1kccdh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrGQK7_LKpMygAtHCftIjxziU6pU_wYBc',
    appId: '1:140632033053:ios:abf3052d1526b698e783f4',
    messagingSenderId: '140632033053',
    projectId: 'groce-ease-e4039',
    storageBucket: 'groce-ease-e4039.appspot.com',
    iosClientId: '140632033053-uv2joh7e2q54vcvkrjqp4f7ok1kccdh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceEase',
  );
}
